mv ion-cli.bash-completion wagerr-cli.bash-completwagerr
mv ion-cli.install wagerr-cli.install
mv ion-cli.manpages wagerr-cli.manpages
mv iond.bash-completion wagerrd.bash-completwagerr
mv iond.desktop wagerrd.desktop
mv ion-dev.bash-completion wagerr-dev.bash-completwagerr
mv ion-dev.install wagerr-dev.install
mv ion-dev.lintian-overrides wagerr-dev.lintian-overrides
mv ion-dev.manpages wagerr-dev.manpages
mv ion-dev.protocol wagerr-dev.protocol
mv iond.examples wagerrd.examples
mv iond.install wagerrd.install
mv iond.lintian-overrides wagerrd.lintian-overrides
mv iond.manpages wagerrd.manpages
mv iond.protocol wagerrd.protocol
mv iond_regtest.bash-completion wagerrd_regtest.bash-completwagerr
mv iond_regtest.desktop wagerrd_regtest.desktop
mv iond_regtest.protocol wagerrd_regtest.protocol
mv iond_testnet.bash-completion wagerrd_testnet.bash-completwagerr
mv iond_testnet.desktop wagerrd_testnet.desktop
mv iond_testnet.protocol wagerrd_testnet.protocol
mv ion-full.bash-completion wagerr-full.bash-completwagerr
mv ion-full.install wagerr-full.install
mv ion-full.lintian-overrides wagerr-full.lintian-overrides
mv ion-full.manpages wagerr-full.manpages
mv ion-full.protocol wagerr-full.protocol
mv ion-qt.desktop wagerr-qt.desktop
mv ion-qt.install wagerr-qt.install
mv ion-qt.lintian-overrides wagerr-qt.lintian-overrides
mv ion-qt.manpages wagerr-qt.manpages
mv ion-qt.protocol wagerr-qt.protocol
mv ion-qt_regtest.desktop wagerr-qt_regtest.desktop
mv ion-qt_regtest.protocol wagerr-qt_regtest.protocol
mv ion-qt_testnet.desktop wagerr-qt_testnet.desktop
mv ion-qt_testnet.protocol wagerr-qt_testnet.protocol
mv ion-tx.bash-completion wagerr-tx.bash-completwagerr
mv ion-tx.install wagerr-tx.install
mv ion-tx.manpages wagerr-tx.manpages
